### ISSUE TITLE
Problem with impacts

### ISSUE THREAD

**Issue by Paschoalino1** [gpiras/sphet#12]
Hello, I'm a PhD student and I'm using the sphet package.

I had a question about the impacts function and I would like to raise this question since I know that this package is under development (including the impacts function).

follow my code using built-in columbus data.

 data(columbus, package="spdep")
> listw <- spdep::nb2listw(col.gal.nb)

> attach(columbus)
> #i'm going direct to regression by sphet

> #SAC (SARAR MODEL)
> SAC.robust <- spreg(INC ~ HOVAL+DISCBD+CP, data=columbus, listw, model="sarar", het=TRUE)

> #LAG MODEL
> SARrobust <- spreg(INC ~ HOVAL+DISCBD+CP, data=columbus, listw, model="lag", het=TRUE)

> #going to my questions about the impacts function

> #FOR SAC MODEL
> W <- as(as_dgRMatrix_listw(listw), "CsparseMatrix")
> Warning message:
>
> Function as_dgRMatrix_listw moved to the spatialreg package
>> trMatc <- trW(W, type="mult")

> Warning message:
> Function trW moved to the spatialreg package

>> effects<- summary(impacts(SAC.robust, tr=trMatc, R=10000), zstats=TRUE, short=TRUE)
>> effects

that didn’t create problems for me and the simulations follow:

> ========================================================
> Simulation results (GSTSLS variance matrix):
> ========================================================

#FOR SAR MODEL
>> effects<- summary(impacts(SARrobust, tr=trMatc, R=10000), zstats=TRUE, short=TRUE)

> that gives me:

> Error in UseMethod("impacts", obj) :
>  no applicable method for 'impacts' applied to an object of class "c('sphet', 'stsls_sphet')".

So, the impacts are not computable.

#One way to compute the impacts is by:

>effects<- summary(spatialreg::impacts(SARrobust, tr=trMatc, R=10000), zstats=TRUE, short=TRUE)
effects

But now, the simulation follow: 

> ========================================================
> Simulation results (IV HAC variance matrix):
> ========================================================

(which left me confused because I did not specify such an attribute in my regression, leaving me in doubt if the standard errors of the regression had also been corrected with HAC.) The same occurs using:

effects<- summary(spatialreg::impacts.stsls(SARrobust, tr=trMatc, R=10000), zstats=TRUE, short=TRUE)
effects.

Through R-sig-Geo I had the advice to use

remotes::install_github("gpiras/sphet")

effects<- impacts(SAC.robust, tr=trMatc, n_mvn=10000, inference=TRUE)
summary(effects)
effects <- impacts(SARrobust, tr=trMatc, n_mvn=10000, inference=TRUE)
summary(effects)

Could you inform me if the updates made and this way of computing the impacts have corrected the impacts and about the IV HAC question.

Thank you. Sorry I expressed something wrong or if I made a mistake.

**Comment by gpiras** [comment]
The impacts calculated from the impacts() function from sphet should be accurate. You might find some differences in the inference with respect to spatialreg.

**Comment by Paschoalino1** [comment]
Thank you Professor. 

For the question of inference, in the latest version of sphet, do the impacts follow the arguments chosen in the regression? I tried to see the help for impacts, but I didn't see any information directed to that, in this case, I think so.

Thank you and congratulations.

**Comment by gpiras** [comment]
yes
