### ISSUE TITLE
SHAC

### ISSUE THREAD

**Issue by Jadamso** [gpiras/sphet#13]
Thanks for making this package.

Please consider either enabling a user to run OLS regressions with SHAC standard errors or provide a separate function; i.e. have both `shac` and `stslshac`.

**Comment by gpiras** [comment]
I am sorry but I don't think I fully understand your suggestion. Look at the help for spreg and the OLS with SHAC st.errors is there. Am I missing something?

**Comment by Jadamso** [comment]
It is there, but I think there is a bug. The general code is complicated to debug myself, but if there was a simpler function just for SHAC se's I may have been able to do it myself. (It may also be easier to use for certain users).

```
library(sphet)
library(spdep)
n <- 200
x <- 1:n
y <- x + rnorm(n)
l1 <- runif(n)
l2 <- runif(n)
xy_dat <- data.frame(x,y,l1,l2)
dnb <- dnearneigh(as.matrix(xy_dat[, c('l1','l2')]), 0, .5)
listw <- nb2listw(dnb, zero.policy=F)
reg <- spreg(y~x, data=xy_dat, listw=listw, model="ols", HAC=T)
```
Returns an error on R version 4.0.2, Platform: x86_64-redhat-linux-gnu (64-bit)
```
Error in spreg(y ~ x, data = xy_dat, listw = listw, model = "ols", HAC = T) : 
  Model should be one of 'ivhac', or 'ols' when HAC is true 
```
