### ISSUE TITLE
Migrate ESRI Shapefile to GPKG

### ISSUE THREAD

**Issue by rsbivand** [gpiras/sphet#19]
`spData` is migrating from ESRI Shapefile to GPKG, so use of ESRI Shapefiles from `spData` in this package also needs to migrate before or by the end of August 2024, when ESRI Shapefiles will be dropped from `spData`. The `spData` declaration in `DESCRIPTION` should be changed to `spData (>= 2.3.1)`. Please also refer to https://github.com/Nowosad/spData/issues/62 for background and further information.

**Comment by rsbivand** [comment]
@gpiras  Please note that ESRI Shapefiles will be removed from `spData` at the end of August. Please address this issue now.

**Comment by gpiras** [comment]
@rsbivand Done.
